<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $banks = [
            [
                'bank_id'    => 63,
                'bank_name'  => 'CRDB BANK LIMITED',
                'short_name' => 'CRDB',
                'sort_code'  => '63',
                'bank_code'  => '003',
                'bi_code'    => '00003026',
                'erp_bc'     => '03',
                'erp_br'     => '14',
                'citi_code'  => '003026',
                'swift_code' => 'CORUTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 64,
                'bank_name'  => 'STANDARD CHARTERED',
                'short_name' => 'STANBIC',
                'sort_code'  => '64',
                'bank_code'  => '005',
                'bi_code'    => '00005087',
                'erp_bc'     => '05',
                'erp_br'     => '83',
                'citi_code'  => '670587',
                'swift_code' => 'SCBLTZTX',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 65,
                'bank_name'  => 'HABIB AFRICAN BANK',
                'short_name' => 'HABIB',
                'sort_code'  => '65',
                'bank_code'  => '018',
                'bi_code'    => '00018001',
                'erp_bc'     => '18',
                'erp_br'     => '01',
                'citi_code'  => '671801',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 66,
                'bank_name'  => 'AMANA BANK',
                'short_name' => 'AMANA',
                'sort_code'  => '66',
                'bank_code'  => '046',
                'bi_code'    => '00046002',
                'erp_bc'     => '46',
                'erp_br'     => '02',
                'citi_code'  => '046002',
                'swift_code' => 'AMNNTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 67,
                'bank_name'  => 'AZANIA BANCORP',
                'short_name' => 'AZANIA',
                'sort_code'  => '67',
                'bank_code'  => '031',
                'bi_code'    => '00031999',
                'erp_bc'     => '31',
                'erp_br'     => '01',
                'citi_code'  => '031999',
                'swift_code' => 'AZANTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 68,
                'bank_name'  => 'TWIGA BANKCORP LIMITED',
                'short_name' => 'TWIGA',
                'sort_code'  => '68',
                'bank_code'  => '099',
                'bi_code'    => '09920001',
                'erp_bc'     => null,
                'erp_br'     => null,
                'citi_code'  => '300000',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 69,
                'bank_name'  => 'AZANIA BANCORP LTD',
                'short_name' => 'AZANIA',
                'sort_code'  => '69',
                'bank_code'  => '031',
                'bi_code'    => '00031999',
                'erp_bc'     => '31',
                'erp_br'     => '01',
                'citi_code'  => '031999',
                'swift_code' => 'AZANTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 70,
                'bank_name'  => 'BOA BANK',
                'short_name' => 'BOA',
                'sort_code'  => '70',
                'bank_code'  => '009',
                'bi_code'    => '00009999',
                'erp_bc'     => '09',
                'erp_br'     => '01',
                'citi_code'  => '009999',
                'swift_code' => 'EUAFTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 71,
                'bank_name'  => 'ECOBANK',
                'short_name' => 'ECOBANK',
                'sort_code'  => '71',
                'bank_code'  => '040',
                'bi_code'    => '00040998',
                'erp_bc'     => '40',
                'erp_br'     => null,
                'citi_code'  => '674001',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 72,
                'bank_name'  => 'NBC',
                'short_name' => 'NBC',
                'sort_code'  => '72',
                'bank_code'  => '015',
                'bi_code'    => '00015001',
                'erp_bc'     => '15',
                'erp_br'     => '01',
                'citi_code'  => '671501',
                'swift_code' => 'NLCBTZTX',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 73,
                'bank_name'  => 'BARCLAYS',
                'short_name' => 'BARCLAYS',
                'sort_code'  => '73',
                'bank_code'  => '020',
                'bi_code'    => '00020001',
                'erp_bc'     => '20',
                'erp_br'     => '01',
                'citi_code'  => '672001',
                'swift_code' => 'BARCTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 74,
                'bank_name'  => 'INTERNATIONAL COMMERCIAL BANK',
                'short_name' => 'ICB',
                'sort_code'  => '74',
                'bank_code'  => '019',
                'bi_code'    => '00019005',
                'erp_bc'     => '19',
                'erp_br'     => '01',
                'citi_code'  => '671905',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 75,
                'bank_name'  => 'EQUITY BANK',
                'short_name' => 'EQUITY',
                'sort_code'  => '75',
                'bank_code'  => '047',
                'bi_code'    => '00047000',
                'erp_bc'     => '47',
                'erp_br'     => '00',
                'citi_code'  => '674700',
                'swift_code' => 'EQBLTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 76,
                'bank_name'  => 'KCB',
                'short_name' => 'KCB',
                'sort_code'  => '76',
                'bank_code'  => '017',
                'bi_code'    => '00017013',
                'erp_bc'     => '17',
                'erp_br'     => '001',
                'citi_code'  => '017013',
                'swift_code' => 'KCBLTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 77,
                'bank_name'  => 'BANC ABC',
                'short_name' => 'ABC',
                'sort_code'  => '77',
                'bank_code'  => '034',
                'bi_code'    => '00034001',
                'erp_bc'     => '34',
                'erp_br'     => null,
                'citi_code'  => '673401',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 78,
                'bank_name'  => 'NMB',
                'short_name' => 'NMB',
                'sort_code'  => '78',
                'bank_code'  => '016',
                'bi_code'    => '00016201',
                'erp_bc'     => '16',
                'erp_br'     => '201',
                'citi_code'  => '016101',
                'swift_code' => 'NMIBTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 79,
                'bank_name'  => 'PBZ',
                'short_name' => 'PBOZ',
                'sort_code'  => '79',
                'bank_code'  => '004',
                'bi_code'    => '00004001',
                'erp_bc'     => '04',
                'erp_br'     => '01',
                'citi_code'  => '004001',
                'swift_code' => 'PBZATZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 80,
                'bank_name'  => 'ACCESS BANK',
                'short_name' => 'ACCESS',
                'sort_code'  => '80',
                'bank_code'  => '035',
                'bi_code'    => '00035001',
                'erp_bc'     => '35',
                'erp_br'     => null,
                'citi_code'  => '035001',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 81,
                'bank_name'  => 'TPB',
                'short_name' => 'TPB',
                'sort_code'  => '81',
                'bank_code'  => '048',
                'bi_code'    => '00048110',
                'erp_bc'     => '48',
                'erp_br'     => '110',
                'citi_code'  => '048007',
                'swift_code' => 'TAPBTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 82,
                'bank_name'  => 'FNB BANK',
                'short_name' => 'FNB',
                'sort_code'  => '82',
                'bank_code'  => '045',
                'bi_code'    => '00045001',
                'erp_bc'     => '45',
                'erp_br'     => '01',
                'citi_code'  => '045001',
                'swift_code' => 'FIRNTZTX',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 83,
                'bank_name'  => 'STANBIC',
                'short_name' => 'STANBIC',
                'sort_code'  => '83',
                'bank_code'  => '006',
                'bi_code'    => '00006000',
                'erp_bc'     => '06',
                'erp_br'     => '02',
                'citi_code'  => '006000',
                'swift_code' => 'SBICTZTX',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 84,
                'bank_name'  => 'EFATHA BANK LTD',
                'short_name' => 'EFATHA',
                'sort_code'  => '84',
                'bank_code'  => '099',
                'bi_code'    => '09990001',
                'erp_bc'     => null,
                'erp_br'     => null,
                'citi_code'  => null,
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 85,
                'bank_name'  => 'CBA',
                'short_name' => 'CBA',
                'sort_code'  => '85',
                'bank_code'  => '023',
                'bi_code'    => '00023001',
                'erp_bc'     => '23',
                'erp_br'     => '01',
                'citi_code'  => '672301',
                'swift_code' => 'CBAFTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 86,
                'bank_name'  => 'EXIM',
                'short_name' => 'EXIM',
                'sort_code'  => '86',
                'bank_code'  => '013',
                'bi_code'    => '00013020',
                'erp_bc'     => '13',
                'erp_br'     => '01',
                'citi_code'  => '671308',
                'swift_code' => 'EXTNTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 87,
                'bank_name'  => 'AKIBA COMMERCIAL BANK',
                'short_name' => 'AKIBA',
                'sort_code'  => '87',
                'bank_code'  => '012',
                'bi_code'    => '00012001',
                'erp_bc'     => '12',
                'erp_br'     => '01',
                'citi_code'  => '671200',
                'swift_code' => 'AKCOTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 108,
                'bank_name'  => 'ABSA BANK TANZANIA LIMITED',
                'short_name' => 'ABSA BANK',
                'sort_code'  => '108',
                'bank_code'  => '020',
                'bi_code'    => '00020001',
                'erp_bc'     => '20',
                'erp_br'     => '01',
                'citi_code'  => '672001',
                'swift_code' => 'BARCTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 109,
                'bank_name'  => 'TANZANIA COMMERCIAL BANK',
                'short_name' => 'TCB',
                'sort_code'  => '109',
                'bank_code'  => '',
                'bi_code'    => '',
                'erp_bc'     => null,
                'erp_br'     => null,
                'citi_code'  => null,
                'swift_code' => 'TAPBTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 128,
                'bank_name'  => 'MWALIMU COMMERCIAL BANK PLC',
                'short_name' => 'MWALIMU',
                'sort_code'  => '128',
                'bank_code'  => '',
                'bi_code'    => '',
                'erp_bc'     => null,
                'erp_br'     => null,
                'citi_code'  => null,
                'swift_code' => 'MWCOTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 88,
                'bank_name'  => 'COVENANT BANK',
                'short_name' => 'COVENANT',
                'sort_code'  => '88',
                'bank_code'  => '049',
                'bi_code'    => '00049001',
                'erp_bc'     => '49',
                'erp_br'     => null,
                'citi_code'  => null,
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 89,
                'bank_name'  => 'NIC BANK',
                'short_name' => 'NIC',
                'sort_code'  => '89',
                'bank_code'  => '026',
                'bi_code'    => '00026004',
                'erp_bc'     => '26',
                'erp_br'     => null,
                'citi_code'  => '026004',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 90,
                'bank_name'  => 'UBL BANK',
                'short_name' => 'UBL',
                'sort_code'  => '90',
                'bank_code'  => '050',
                'bi_code'    => '00050001',
                'erp_bc'     => '50',
                'erp_br'     => null,
                'citi_code'  => '675001',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 91,
                'bank_name'  => 'FBME',
                'short_name' => 'FBME',
                'sort_code'  => '91',
                'bank_code'  => '025',
                'bi_code'    => '00025001',
                'erp_bc'     => '25',
                'erp_br'     => '01',
                'citi_code'  => null,
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 92,
                'bank_name'  => 'UBA',
                'short_name' => 'UBA',
                'sort_code'  => '92',
                'bank_code'  => '038',
                'bi_code'    => '00038601',
                'erp_bc'     => '38',
                'erp_br'     => '02',
                'citi_code'  => '673802',
                'swift_code' => 'UNAFTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 93,
                'bank_name'  => 'BANK M',
                'short_name' => 'BANK M',
                'sort_code'  => '93',
                'bank_code'  => '033',
                'bi_code'    => '00033001',
                'erp_bc'     => '33',
                'erp_br'     => '01',
                'citi_code'  => null,
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 94,
                'bank_name'  => 'DIAMOND TRUST BANK',
                'short_name' => 'DTB',
                'sort_code'  => '94',
                'bank_code'  => '011',
                'bi_code'    => '00011001',
                'erp_bc'     => '11',
                'erp_br'     => '02',
                'citi_code'  => '671104',
                'swift_code' => 'DTKETZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 95,
                'bank_name'  => 'CITI BANK',
                'short_name' => 'Citi',
                'sort_code'  => '95',
                'bank_code'  => '008',
                'bi_code'    => '00008001',
                'erp_bc'     => '08',
                'erp_br'     => '01',
                'citi_code'  => '670801',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 96,
                'bank_name'  => 'I & M BANK',
                'short_name' => 'I&M',
                'sort_code'  => '96',
                'bank_code'  => '021',
                'bi_code'    => '00021004',
                'erp_bc'     => '21',
                'erp_br'     => null,
                'citi_code'  => '021004',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 97,
                'bank_name'  => 'BANK OF BARODA',
                'short_name' => 'Baroda',
                'sort_code'  => '97',
                'bank_code'  => '029',
                'bi_code'    => '00029001',
                'erp_bc'     => '29',
                'erp_br'     => '01',
                'citi_code'  => '029001',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 98,
                'bank_name'  => 'BANK OF INDIA',
                'short_name' => 'BOI',
                'sort_code'  => '98',
                'bank_code'  => '036',
                'bi_code'    => '00036003',
                'erp_bc'     => '036',
                'erp_br'     => null,
                'citi_code'  => '673601',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 99,
                'bank_name'  => 'DCB BANK',
                'short_name' => 'DCB',
                'sort_code'  => '99',
                'bank_code'  => '024',
                'bi_code'    => '00024002',
                'erp_bc'     => '024',
                'erp_br'     => '002',
                'citi_code'  => '024002',
                'swift_code' => 'DASUTZTZ',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 100,
                'bank_name'  => 'MKOMBOZI COMMERCIAL BANK',
                'short_name' => 'MKOMBOZI',
                'sort_code'  => '100',
                'bank_code'  => '039',
                'bi_code'    => '00039099',
                'erp_bc'     => '39',
                'erp_br'     => null,
                'citi_code'  => '673901',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 101,
                'bank_name'  => 'BANK OF TANZANIA',
                'short_name' => 'BOT',
                'sort_code'  => '101',
                'bank_code'  => '001',
                'bi_code'    => '00001001',
                'erp_bc'     => '01',
                'erp_br'     => '01',
                'citi_code'  => '001001',
                'swift_code' => 'TANZTZTX',
                'is_active'  => true,
                'created_at' => now(),
            ],
            [
                'bank_id'    => 102,
                'bank_name'  => 'MAENDELEO BANK',
                'short_name' => 'MAENDELEO',
                'sort_code'  => '102',
                'bank_code'  => '051',
                'bi_code'    => '00051001',
                'erp_bc'     => '51',
                'erp_br'     => null,
                'citi_code'  => '051003',
                'swift_code' => null,
                'is_active'  => true,
                'created_at' => now(),
            ],
        ];

        foreach ($banks as $bank) {
            DB::connection('bcmis2')
                ->table('bank')
                ->updateOrInsert(
                    ['bank_id' => $bank['bank_id']],
                    $bank
                );
        }

        $this->command?->info('Banks seeded successfully into bcmis2.bank.');
    }
}


