<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BridgeModuleMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::connection('bcmis2')
            ->table('bridge_module_menu')
            ->upsert(
                [
                    [
                        'id' => 1,
                        'module_id' => 2,
                        'menu_name' => 'Employee Profile',
                        'menu_path' => '/employee-management/profile',
                        'menu_icon' => 'UserCircle',
                        'menu_order' => 1,
                        'menu_description' => 'Display employee information',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 2,
                        'module_id' => 2,
                        'menu_name' => 'Register Employee',
                        'menu_path' => '/employee-management/registration',
                        'menu_icon' => 'Users',
                        'menu_order' => 2,
                        'menu_description' => 'Registering Employee',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 3,
                        'module_id' => 2,
                        'menu_name' => 'Manage Employee',
                        'menu_path' => '/employee-management/manage-employee',
                        'menu_icon' => 'UserCog',
                        'menu_order' => 3,
                        'menu_description' => 'Managing and supervision of staff',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 4,
                        'module_id' => 2,
                        'menu_name' => 'Employee Attendance',
                        'menu_path' => '/employee-management/attendance',
                        'menu_icon' => 'Calendar',
                        'menu_order' => 4,
                        'menu_description' => 'Staff attendance details',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 5,
                        'module_id' => 2,
                        'menu_name' => 'Reports',
                        'menu_path' => '/employee-management/attendance-report',
                        'menu_icon' => 'FileText',
                        'menu_order' => 5,
                        'menu_description' => 'Generate employees attendance reports',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 6,
                        'module_id' => 8,
                        'menu_name' => 'Roles',
                        'menu_path' => '/admin-management/role-management',
                        'menu_icon' => 'UserCheck',
                        'menu_order' => 1,
                        'menu_description' => 'Manages system roles',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 7,
                        'module_id' => 8,
                        'menu_name' => 'Permission',
                        'menu_path' => '/admin-management/permission-management',
                        'menu_icon' => 'Shield',
                        'menu_order' => 2,
                        'menu_description' => 'Manages system permission',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 8,
                        'module_id' => 8,
                        'menu_name' => 'Grant Role',
                        'menu_path' => '/admin-management/grant-role',
                        'menu_icon' => 'UserCheck',
                        'menu_order' => 3,
                        'menu_description' => 'Assign role to employee',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 9,
                        'module_id' => 8,
                        'menu_name' => 'Register Module',
                        'menu_path' => '/admin-management/register-module',
                        'menu_icon' => 'AppWindow',
                        'menu_order' => 4,
                        'menu_description' => 'Managing module registration',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 10,
                        'module_id' => 8,
                        'menu_name' => 'Module Menu',
                        'menu_path' => '/admin-management/module-menu',
                        'menu_icon' => 'Menu',
                        'menu_order' => 5,
                        'menu_description' => 'Manages menus per module',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 11,
                        'module_id' => 8,
                        'menu_name' => 'Role Module Menu',
                        'menu_path' => '/admin-management/role-module-menu',
                        'menu_icon' => 'Link2',
                        'menu_order' => 6,
                        'menu_description' => 'Manages Role on module and menu',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 12,
                        'module_id' => 6,
                        'menu_name' => 'Educational Level',
                        'menu_path' => '/allowance-management/educational-level',
                        'menu_icon' => 'GraduationCap',
                        'menu_order' => 1,
                        'menu_description' => 'Manages educational levels',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 13,
                        'module_id' => 6,
                        'menu_name' => 'Apply Overtime',
                        'menu_path' => '/allowance-management/overtime-management',
                        'menu_icon' => 'Clock',
                        'menu_order' => 2,
                        'menu_description' => 'Request overtime',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 14,
                        'module_id' => 6,
                        'menu_name' => 'Manage Overtime',
                        'menu_path' => '/allowance-management/manage-overtime',
                        'menu_icon' => 'Clock',
                        'menu_order' => 3,
                        'menu_description' => 'Manages employee overtime requests',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 15,
                        'module_id' => 6,
                        'menu_name' => 'Manage Overtime Rates',
                        'menu_path' => '/allowance-management/overtime-rates',
                        'menu_icon' => 'DollarSign',
                        'menu_order' => 4,
                        'menu_description' => 'Manages Overtime rates per educational level',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 16,
                        'module_id' => 4,
                        'menu_name' => 'Manage Application',
                        'menu_path' => '/leave-management/application',
                        'menu_icon' => 'ClipboardList',
                        'menu_order' => 1,
                        'menu_description' => 'Apply for leave and track leave requests',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 33,
                        'module_id' => 4,
                        'menu_name' => 'Manage Balance',
                        'menu_path' => '/leave-management/balance',
                        'menu_icon' => 'Scale',
                        'menu_order' => 2,
                        'menu_description' => 'View entitled, used, and remaining leave days',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 34,
                        'module_id' => 4,
                        'menu_name' => 'Manage Reports',
                        'menu_path' => '/leave-management/reports',
                        'menu_icon' => 'BarChart3',
                        'menu_order' => 3,
                        'menu_description' => 'Leave applications and status reports',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 17,
                        'module_id' => 5,
                        'menu_name' => 'Payroll Management',
                        'menu_path' => '/payroll-management',
                        'menu_icon' => 'Wallet',
                        'menu_order' => 1,
                        'menu_description' => 'Salaries information and processing',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 18,
                        'module_id' => 3,
                        'menu_name' => 'Toll Management',
                        'menu_path' => '/collection-management',
                        'menu_icon' => 'Building2',
                        'menu_order' => 1,
                        'menu_description' => 'Manages Bridge collection',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 19,
                        'module_id' => 7,
                        'menu_name' => 'Incident Management',
                        'menu_path' => '/incident-management',
                        'menu_icon' => 'AlertTriangle',
                        'menu_order' => 1,
                        'menu_description' => 'Manages bridge incidents',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 20,
                        'module_id' => 5,
                        'menu_name' => 'Payroll Processing',
                        'menu_path' => '/payroll-management/runs',
                        'menu_icon' => '<BarChart3 size={20} />',
                        'menu_order' => null,
                        'menu_description' => 'Payroll processing menu',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 21,
                        'module_id' => 5,
                        'menu_name' => 'Manage Deductions',
                        'menu_path' => '/payroll-management/deductions',
                        'menu_icon' => '<Landmark size={20} />',
                        'menu_order' => null,
                        'menu_description' => null,
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 22,
                        'module_id' => 5,
                        'menu_name' => 'Manage Benefits',
                        'menu_path' => '/payroll-management/benefits',
                        'menu_icon' => null,
                        'menu_order' => null,
                        'menu_description' => null,
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 23,
                        'module_id' => 5,
                        'menu_name' => 'Manage Loan',
                        'menu_path' => '/payroll-management/loan-management',
                        'menu_icon' => '<Wallet size={20} />',
                        'menu_order' => null,
                        'menu_description' => null,
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 24,
                        'module_id' => 5,
                        'menu_name' => 'Manage Arrears',
                        'menu_path' => '/payroll-management/arrears',
                        'menu_icon' => '<DollarSign size={20} />',
                        'menu_order' => null,
                        'menu_description' => null,
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 25,
                        'module_id' => 5,
                        'menu_name' => 'Payslips',
                        'menu_path' => '/payroll-management/payslips',
                        'menu_icon' => '<FileText size={20} />',
                        'menu_order' => null,
                        'menu_description' => null,
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 26,
                        'module_id' => 5,
                        'menu_name' => 'Payroll Reports',
                        'menu_path' => '/payroll-management/payroll-reports',
                        'menu_icon' => '<BarChart3 size={20} />',
                        'menu_order' => null,
                        'menu_description' => 'Process Payroll Reports',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 27,
                        'module_id' => 6,
                        'menu_name' => 'Manage Special Task',
                        'menu_path' => '/allowance-management/special-tasks',
                        'menu_icon' => '<Briefcase size={20} />',
                        'menu_order' => null,
                        'menu_description' => 'Managing Special Tasks',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 28,
                        'module_id' => 6,
                        'menu_name' => 'Upload Memo',
                        'menu_path' => '/allowance-management/overtime-submission-documents',
                        'menu_icon' => '<FileText size={20} />',
                        'menu_order' => null,
                        'menu_description' => null,
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 29,
                        'module_id' => 6,
                        'menu_name' => 'Apply Special Task',
                        'menu_path' => '/allowance-management/my-special-tasks',
                        'menu_icon' => '<Briefcase size={20} />',
                        'menu_order' => null,
                        'menu_description' => null,
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 30,
                        'module_id' => 6,
                        'menu_name' => 'Manage Holiday',
                        'menu_path' => '/allowance-management/public-holidays',
                        'menu_icon' => '<Calendar size={20} />',
                        'menu_order' => null,
                        'menu_description' => null,
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-01 00:40:37',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 31,
                        'module_id' => 10,
                        'menu_name' => 'Configuration',
                        'menu_path' => '/administration-management/configuration',
                        'menu_icon' => 'Settings',
                        'menu_order' => 1,
                        'menu_description' => 'System configuration hub',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-08 00:00:00',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                    [
                        'id' => 32,
                        'module_id' => 10,
                        'menu_name' => 'Report Engine',
                        'menu_path' => '/administration-management/report-engine',
                        'menu_icon' => 'BarChart3',
                        'menu_order' => 2,
                        'menu_description' => 'Manage report modules and definitions',
                        'is_active' => true,
                        'created_by' => 1,
                        'created_at' => '2026-07-08 00:00:00',
                        'modified_by' => null,
                        'modified_at' => null,
                    ],
                ],
                ['id'],
                [
                    'module_id',
                    'menu_name',
                    'menu_path',
                    'menu_icon',
                    'menu_order',
                    'menu_description',
                    'is_active',
                    'modified_by',
                    'modified_at',
                ]
            );

        $this->command?->info('Bridge module menus seeded successfully into bcmis2.bridge_module_menu.');
    }
}
