import jsPDF from 'jspdf';
import dayjs from 'dayjs';
import logoUrl from '../../assets/images/logo.png';
import { formatCount, formatMoneyForExport, isMoneyField } from './numberFormat.js';

export const BMS_SYSTEM_NAME = 'Bridge Management System';
export const BMS_ORG_NAME = 'National Social Security Fund';

const BRAND_RGB = [150, 46, 50];
const BRAND_DARK_RGB = [122, 35, 38];
const SOFT_RGB = [255, 245, 245];
const BORDER_RGB = [226, 232, 240];
const TEXT_RGB = [15, 23, 42];
const MUTED_RGB = [100, 116, 139];
const WHITE = [255, 255, 255];

const PAGE_MARGIN = 14;

let logoDataUrlCache = null;

async function loadLogoDataUrl() {
  if (logoDataUrlCache) return logoDataUrlCache;
  const response = await fetch(logoUrl);
  const blob = await response.blob();
  logoDataUrlCache = await new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
  return logoDataUrlCache;
}

function truncateText(doc, text, maxWidth) {
  const str = String(text ?? '');
  if (!str) return '';
  if (doc.getTextWidth(str) <= maxWidth) return str;
  let trimmed = str;
  while (trimmed.length > 1 && doc.getTextWidth(`${trimmed}…`) > maxWidth) {
    trimmed = trimmed.slice(0, -1);
  }
  return `${trimmed}…`;
}

function formatPdfCellValue(value, columnKey) {
  if (value === null || value === undefined || value === '') return 'N/A';
  if (columnKey && isMoneyField(columnKey)) return formatMoneyForExport(value);
  if (
    columnKey &&
    /^(count|vehicles|vehiclecount|total_vehicle|daily_bundle|weekly_bundle|monthly_bundle)$/i.test(
      String(columnKey)
    )
  ) {
    return formatCount(value);
  }
  if (typeof value === 'number') return formatCount(value);
  return String(value);
}

function resolveRowValue(row, column, resolveOperatorCell) {
  if (column.key === 'operator_name' && resolveOperatorCell) {
    return resolveOperatorCell(row);
  }
  return row[column.key];
}

function drawBrandHeader(doc, { reportTitle, filterLines, generatedAt, generatedBy, logoDataUrl }) {
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = PAGE_MARGIN;

  const logoSize = 22;
  const logoX = (pageWidth - logoSize) / 2;
  if (logoDataUrl) {
    try {
      doc.addImage(logoDataUrl, 'PNG', logoX, y, logoSize, logoSize);
    } catch {
      // Continue without logo if image fails to render.
    }
  }
  y += logoSize + 5;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...BRAND_RGB);
  doc.text(BMS_SYSTEM_NAME, pageWidth / 2, y, { align: 'center' });
  y += 5;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...MUTED_RGB);
  doc.text(BMS_ORG_NAME, pageWidth / 2, y, { align: 'center' });
  y += 4.5;

  doc.setFontSize(8);
  doc.text('Toll Collection & Operations Reporting', pageWidth / 2, y, { align: 'center' });
  y += 8;

  doc.setFillColor(...SOFT_RGB);
  doc.setDrawColor(...BORDER_RGB);
  const titleBlockHeight = 14;
  doc.roundedRect(PAGE_MARGIN, y, pageWidth - PAGE_MARGIN * 2, titleBlockHeight, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...BRAND_DARK_RGB);
  doc.text(reportTitle, pageWidth / 2, y + 8, { align: 'center' });

  y += titleBlockHeight + 4;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...TEXT_RGB);
  doc.text(`Generated by: ${generatedBy}`, PAGE_MARGIN, y);
  doc.text(`Generated: ${generatedAt}`, pageWidth - PAGE_MARGIN, y, { align: 'right' });
  y += 5;

  if (filterLines.length > 0) {
    const filterLabel = 'Filters applied';
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...BRAND_RGB);
    doc.text(filterLabel, PAGE_MARGIN, y);
    y += 4;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_RGB);

    const colWidth = (pageWidth - PAGE_MARGIN * 2) / 2;
    const startY = y;
    filterLines.forEach((line, index) => {
      const col = index % 2;
      const row = Math.floor(index / 2);
      const x = PAGE_MARGIN + col * colWidth;
      const lineY = startY + row * 4.5;
      const text = `${line.label}: ${line.value}`;
      doc.text(truncateText(doc, text, colWidth - 4), x, lineY);
    });
    y = startY + Math.ceil(filterLines.length / 2) * 4.5 + 2;
  }

  return y;
}

function drawTable(doc, startY, columns, rows, resolveOperatorCell) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const tableWidth = pageWidth - PAGE_MARGIN * 2;
  const serialColWidth = 10;
  const dataColWidth = (tableWidth - serialColWidth) / Math.max(columns.length, 1);
  const colWidths = [serialColWidth, ...columns.map(() => dataColWidth)];
  const rowHeight = 7;
  const headerHeight = 8;
  let y = startY;

  const drawHeader = () => {
    doc.setFillColor(...BRAND_RGB);
    doc.rect(PAGE_MARGIN, y, tableWidth, headerHeight, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(...WHITE);

    let x = PAGE_MARGIN + 2;
    doc.text('#', x, y + 5.5);
    x += colWidths[0];
    columns.forEach((col, idx) => {
      doc.text(truncateText(doc, col.title, colWidths[idx + 1] - 2), x + 1, y + 5.5);
      x += colWidths[idx + 1];
    });
    y += headerHeight;
  };

  const ensureSpace = (needed) => {
    if (y + needed <= pageHeight - 16) return;
    doc.addPage();
    y = PAGE_MARGIN + 6;
    drawHeader();
  };

  drawHeader();

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...TEXT_RGB);

  rows.forEach((row, rowIndex) => {
    ensureSpace(rowHeight);
    if (rowIndex % 2 === 0) {
      doc.setFillColor(...SOFT_RGB);
      doc.rect(PAGE_MARGIN, y, tableWidth, rowHeight, 'F');
    }

    doc.setDrawColor(...BORDER_RGB);
    doc.line(PAGE_MARGIN, y + rowHeight, PAGE_MARGIN + tableWidth, y + rowHeight);

    let x = PAGE_MARGIN + 2;
    doc.text(String(rowIndex + 1), x, y + 5);
    x += colWidths[0];

    columns.forEach((col, idx) => {
      const raw = resolveRowValue(row, col, resolveOperatorCell);
      const text = formatPdfCellValue(raw, col.key);
      const alignRight = isMoneyField(col.key);
      const cellText = truncateText(doc, text, colWidths[idx + 1] - 2);
      if (alignRight) {
        doc.text(cellText, x + colWidths[idx + 1] - 2, y + 5, { align: 'right' });
      } else {
        doc.text(cellText, x + 1, y + 5);
      }
      x += colWidths[idx + 1];
    });

    y += rowHeight;
  });

  return y + 4;
}

function drawFooter(doc) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setDrawColor(...BORDER_RGB);
    doc.line(PAGE_MARGIN, pageHeight - 12, pageWidth - PAGE_MARGIN, pageHeight - 12);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...MUTED_RGB);
    doc.text(BMS_SYSTEM_NAME, PAGE_MARGIN, pageHeight - 7);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 7, { align: 'center' });
    doc.text(dayjs().format('YYYY-MM-DD HH:mm'), pageWidth - PAGE_MARGIN, pageHeight - 7, {
      align: 'right',
    });
  }
}

/**
 * Export collection report rows to a branded PDF document.
 */
export async function exportCollectionReportPdf({
  report,
  rows,
  cancelledRows = [],
  filterLines = [],
  meta = null,
  resolveOperatorCell,
  generatedBy = 'Unknown user',
}) {
  const columns = report?.columns ?? [];
  const orientation = columns.length > 5 ? 'landscape' : 'portrait';
  const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });
  const logoDataUrl = await loadLogoDataUrl();
  const generatedAt = dayjs().format('DD MMM YYYY, HH:mm');

  let y = drawBrandHeader(doc, {
    reportTitle: report?.label ?? 'Report',
    filterLines,
    generatedAt,
    generatedBy,
    logoDataUrl,
  });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...MUTED_RGB);
  doc.text(`${rows.length.toLocaleString()} record${rows.length === 1 ? '' : 's'}`, PAGE_MARGIN, y);
  y += 5;

  if (meta) {
    const metaParts = [
      meta.shift && `Shift: ${meta.shift}`,
      meta.shift_date && `Date: ${meta.shift_date}`,
      meta.operator_name && `Operator: ${meta.operator_name}`,
      meta.billing_amount && `Total: TZS ${meta.billing_amount}`,
    ].filter(Boolean);
    if (metaParts.length > 0) {
      doc.text(metaParts.join(' · '), PAGE_MARGIN, y);
      y += 5;
    }
  }

  y = drawTable(doc, y, columns, rows, resolveOperatorCell);

  if (cancelledRows.length > 0) {
    const pageHeight = doc.internal.pageSize.getHeight();
    if (y > pageHeight - 40) {
      doc.addPage();
      y = PAGE_MARGIN + 6;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...BRAND_RGB);
    doc.text('Cancelled Receipts', PAGE_MARGIN, y);
    y += 6;

    const cancelColumns = [
      { title: 'Plate', key: 'plate_no' },
      { title: 'Receipt', key: 'receipt_num' },
      { title: 'Amount', key: 'charged_amount' },
      { title: 'Reason', key: 'reason' },
    ];
    y = drawTable(doc, y, cancelColumns, cancelledRows);
  }

  drawFooter(doc);

  const ts = dayjs().format('YYYYMMDD-HHmmss');
  const slug = (report?.id ?? 'report').replace(/[^\w-]+/g, '_');
  doc.save(`${slug}_${ts}.pdf`);
}
