<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateOverloadFineTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('overload_fine', function(Blueprint $table)
		{
			$table->bigInteger('id', true)->comment('Bill_ID');
			$table->string('first_name', 100)->comment('PAYER FIRST NAME');
			$table->string('middle_name', 100)->nullable()->comment('PAYER SECOND NAME');
			$table->string('surname', 100)->comment('PAYER SURNAME');
			$table->string('vehicle_num', 100)->comment('PAYER ID');
			$table->string('pyr_cell_num', 100)->comment('PAYER CELL NUM');
			$table->string('pyr_email', 100)->comment('PAYER EMAIL');
			$table->string('bill_desc', 500)->nullable();
			$table->float('bill_amount', 10, 0);
			$table->dateTime('bill_exp_dt')->nullable()->comment('BILL EXPIRED DATE');
			$table->string('contr_num', 100)->nullable()->comment('CONTROL NUM');
			$table->string('ticket_num', 50)->nullable();
			$table->string('ctr_acc_num', 100)->nullable()->comment('CREDIT ACCOUNT NUM');
			$table->string('tin_number', 100)->nullable();
			$table->string('bill_status', 100)->nullable()->default('0');
			$table->integer('bill_gen_by')->nullable()->comment('BILL GENERATED BY');
			$table->dateTime('bill_gen_at')->nullable()->comment('BILL GENERATED DT');
			$table->integer('bill_cancel_by')->nullable()->comment('DEACTIVATED BY');
			$table->string('cancel_reason', 100)->nullable();
			$table->dateTime('bill_cancel_date')->nullable()->comment('DEACTIVATED AT');
			$table->string('is_cancelled', 100)->nullable()->default('0')->comment('IS DEACTIVATED');
			$table->string('trx_id', 100)->nullable()->comment('TRANSACTION ID');
			$table->dateTime('trx_dt_tm')->nullable()->comment('TRANSACTION DT');
			$table->string('usd_pay_chn', 100)->nullable()->comment('USED PAYMENT CHANNEL');
			$table->string('psp_receipt_num', 100)->nullable()->comment('PAYMENT SERVICE PROVIDER RECEIPT NUM');
			$table->string('psp_name', 100)->nullable()->comment('PAYMENT SERVICE PROVIDER NAME');
			$table->integer('receipt_type')->nullable()->default(3);
			$table->string('t_status', 50)->nullable();
			$table->string('error_code', 50)->nullable();
			$table->dateTime('updated_at')->nullable();
			$table->integer('payment_method')->nullable()->default(3);
			$table->integer('collection_office')->nullable()->default(1);
			$table->string('receipt_number', 20)->nullable();
			$table->string('pay_ref_id', 25)->nullable();
			$table->integer('erp_status')->nullable();
			$table->dateTime('receipt_date')->nullable();
			$table->dateTime('payment_date')->nullable();
			$table->integer('updated_by')->nullable();
			$table->float('paid_amt', 10, 0)->nullable();
			$table->string('pyr_name', 50)->nullable();
			$table->integer('http_status')->nullable();
			$table->string('source', 200)->nullable();
		});
	}


	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('overload_fine');
	}

}
