export const REPORT_CATEGORY_OPTIONS = [
  { value: 'collection', label: 'Collection' },
  { value: 'shift', label: 'Shift' },
  { value: 'payment', label: 'Payment' },
  { value: 'audit', label: 'Audit' },
];

export const REPORT_FILTER_OPTIONS = [
  { value: 'from_date', label: 'From Date' },
  { value: 'to_date', label: 'To Date' },
  { value: 'shift_id', label: 'Shift' },
  { value: 'shift_date', label: 'Shift Date' },
  { value: 'body_type', label: 'Body Type' },
  { value: 'body_type_id', label: 'Body Type ID' },
  { value: 'lane', label: 'Lane / Booth' },
  { value: 'lane_id', label: 'Lane ID' },
  { value: 'operator', label: 'Operator' },
  { value: 'user_id', label: 'Operator (user_id)' },
  { value: 'counter_date', label: 'Counter Date' },
  { value: 'open_counter', label: 'Open Counter' },
  { value: 'close_counter', label: 'Close Counter' },
  { value: 'options', label: 'Report Option' },
  { value: 'collection_type', label: 'Collection Type' },
  { value: 'year', label: 'Year' },
];

export const KNOWN_HANDLERS = [
  'daily-collection',
  'daily-shift-collection',
  'body-type-collection',
  'booth-collection',
  'body-type-audit',
  'exempted-vehicles',
  'daily-cashless',
  'body-cashless',
  'cancelled-transactions',
  'bundle-collection',
  'bundle-registration',
  'bundle-subscription',
  'vehicle-passage',
  'vehicle-passage/paginated',
  'toll-collection-detail',
  'payment-reconciliation',
  'end-of-shift-overall',
  'shift-summary',
  'shift-summary-audit',
  'toll-collection-summary',
  'incident-collection-summary',
  'overload-collection-summary',
  'event-collection-summary',
  'monthly-collection-summary',
  'shift-collection',
];
